### ISSUE TITLE
webgl flickering on ios device

### ISSUE THREAD

**Issue by qDev-hue** [smpnjn/webgl-apple-cards#1]
Hi there,

Learned a lot from your tutorial. Tested the code on ios and there is a lot of flickering (safari, chrome, firefox). Wondering if there were some techniques to mitigate the flickering? I've tried changing the THREE.WebGLRenderer properties, but unfortunately that doesn't seem to solve the flickering issue. Any thoughts? Thank you!

**Comment by smpnjn** [comment]
Hey, I will look into this. A cursory glance at google indicates it's a common issue with iOS, but not sure what's causing it. Will try and see if there's an easy solution. Let me know if you have any luck as well.

**Comment by qDev-hue** [comment]
My guess is that the answer lies somewhere in the animate function being unable to account for canvas or element resizes. When you pinch zoom on ios the flickering/blinking gets really intense

https://stackoverflow.com/questions/17779134/how-do-you-resize-a-canvas-without-flicker

Also seems to be ios specific, tested on an android device and everything seemed fine (no flickering/blinking)

**Comment by smpnjn** [comment]
I think the issue is that when using appendChild in animate(), iOS is probably lagging a little bit, meaning we don't immediately get to see the canvas and it flickers. I've made a change which seems to have resolved the issue and pushed it to the repo, to only append the canvas once and then update its renders. Feel free to pull or clone.

Seems to have fixed it for me, but you can let me know.

**Comment by qDev-hue** [comment]
Yup the recent commit fixed it! Thank you! I'll read up some more on this

https://github.com/smpnjn/webgl-apple-cards/commit/00c79148da5a4130b9b93d507a991fa0ac151f59
